# Generated by Django 5.0.4 on 2024-05-11 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OJTHiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('theme', models.CharField(default='', max_length=150)),
                ('date_of_event', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='OJTRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_disclosure', models.BooleanField(default=False)),
                ('biodata', models.BooleanField(default=False)),
                ('parents_consent', models.BooleanField(default=False)),
                ('application_letter', models.BooleanField(default=False)),
                ('medical', models.BooleanField(default=False)),
                ('moa', models.BooleanField(default=False)),
                ('endorsement', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerGuidanceTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seminar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobplacement.seminar')),
            ],
        ),
    ]
